name: update_manager
description: "A Flutter package for managing app updates"
version: 1.0.0
homepage: "https://github.com/jayadevpanthaplavil/update-manager"
repository: "https://github.com/jayadevpanthaplavil/update-manager"
issue_tracker: "https://github.com/jayadevpanthaplavil/update-manager/issues"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_remote_config: ^6.0.2

  # Shorebird
  shorebird_code_push: ^2.0.5

  # App Info
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:

topics:
  - updates
  - versioning
  - remote-config
  - firebase
  - app-management

false_secrets:
  - example/**

flutter:
